// Municipios de Colombia agrupados por departamento
// Fuente: DANE - División Político-Administrativa de Colombia

export interface Municipio {
  value: string
  label: string
  departamento: string
}

export const MUNICIPIOS: Municipio[] = [
  // Amazonas
  { value: "LETICIA", label: "Leticia", departamento: "Amazonas" },
  { value: "PUERTO_NARINO", label: "Puerto Nariño", departamento: "Amazonas" },

  // Antioquia
  { value: "MEDELLIN", label: "Medellín", departamento: "Antioquia" },
  { value: "ABEJORRAL", label: "Abejorral", departamento: "Antioquia" },
  { value: "ABRIAQUI", label: "Abriaquí", departamento: "Antioquia" },
  { value: "ALEJANDRIA", label: "Alejandría", departamento: "Antioquia" },
  { value: "AMAGA", label: "Amagá", departamento: "Antioquia" },
  { value: "AMALFI", label: "Amalfi", departamento: "Antioquia" },
  { value: "ANDES", label: "Andes", departamento: "Antioquia" },
  { value: "ANGELOPOLIS", label: "Angelópolis", departamento: "Antioquia" },
  { value: "ANGOSTURA", label: "Angostura", departamento: "Antioquia" },
  { value: "ANORI", label: "Anorí", departamento: "Antioquia" },
  { value: "ANZA", label: "Anzá", departamento: "Antioquia" },
  { value: "APARTADO", label: "Apartadó", departamento: "Antioquia" },
  { value: "ARBOLETES", label: "Arboletes", departamento: "Antioquia" },
  { value: "ARGELIA", label: "Argelia", departamento: "Antioquia" },
  { value: "ARMENIA", label: "Armenia", departamento: "Antioquia" },
  { value: "BARBOSA", label: "Barbosa", departamento: "Antioquia" },
  { value: "BELLO", label: "Bello", departamento: "Antioquia" },
  { value: "BELMIRA", label: "Belmira", departamento: "Antioquia" },
  { value: "BETANIA", label: "Betania", departamento: "Antioquia" },
  { value: "BETULIA", label: "Betulia", departamento: "Antioquia" },
  { value: "BRICENO", label: "Briceño", departamento: "Antioquia" },
  { value: "BURITICA", label: "Buriticá", departamento: "Antioquia" },
  { value: "CACERES", label: "Cáceres", departamento: "Antioquia" },
  { value: "CAICEDO", label: "Caicedo", departamento: "Antioquia" },
  { value: "CALDAS", label: "Caldas", departamento: "Antioquia" },
  { value: "CAMPAMENTO", label: "Campamento", departamento: "Antioquia" },
  { value: "CANASGORDAS", label: "Cañasgordas", departamento: "Antioquia" },
  { value: "CARACOLI", label: "Caracolí", departamento: "Antioquia" },
  { value: "CARAMANTA", label: "Caramanta", departamento: "Antioquia" },
  { value: "CAREPA", label: "Carepa", departamento: "Antioquia" },
  { value: "CARMEN_DE_VIBORAL", label: "Carmen de Viboral", departamento: "Antioquia" },
  { value: "CAROLINA", label: "Carolina del Príncipe", departamento: "Antioquia" },
  { value: "CAUCASIA", label: "Caucasia", departamento: "Antioquia" },
  { value: "CHIGORODO", label: "Chigorodó", departamento: "Antioquia" },
  { value: "CISNEROS", label: "Cisneros", departamento: "Antioquia" },
  { value: "CIUDAD_BOLIVAR", label: "Ciudad Bolívar", departamento: "Antioquia" },
  { value: "COCORNA", label: "Cocorná", departamento: "Antioquia" },
  { value: "CONCEPCION", label: "Concepción", departamento: "Antioquia" },
  { value: "CONCORDIA", label: "Concordia", departamento: "Antioquia" },
  { value: "COPACABANA", label: "Copacabana", departamento: "Antioquia" },
  { value: "DABEIBA", label: "Dabeiba", departamento: "Antioquia" },
  { value: "DONMATIAS", label: "Donmatías", departamento: "Antioquia" },
  { value: "EBEJICO", label: "Ebéjico", departamento: "Antioquia" },
  { value: "EL_BAGRE", label: "El Bagre", departamento: "Antioquia" },
  { value: "EL_SANTUARIO", label: "El Santuario", departamento: "Antioquia" },
  { value: "ENVIGADO", label: "Envigado", departamento: "Antioquia" },
  { value: "FREDONIA", label: "Fredonia", departamento: "Antioquia" },
  { value: "FRONTINO", label: "Frontino", departamento: "Antioquia" },
  { value: "GIRALDO", label: "Giraldo", departamento: "Antioquia" },
  { value: "GIRARDOTA", label: "Girardota", departamento: "Antioquia" },
  { value: "GOMEZ_PLATA", label: "Gómez Plata", departamento: "Antioquia" },
  { value: "GRANADA", label: "Granada", departamento: "Antioquia" },
  { value: "GUADALUPE", label: "Guadalupe", departamento: "Antioquia" },
  { value: "GUARNE", label: "Guarne", departamento: "Antioquia" },
  { value: "GUATAPE", label: "Guatapé", departamento: "Antioquia" },
  { value: "HELICONIA", label: "Heliconia", departamento: "Antioquia" },
  { value: "HISPANIA", label: "Hispania", departamento: "Antioquia" },
  { value: "ITAGUI", label: "Itagüí", departamento: "Antioquia" },
  { value: "ITUANGO", label: "Ituango", departamento: "Antioquia" },
  { value: "JARDIN", label: "Jardín", departamento: "Antioquia" },
  { value: "JERICO", label: "Jericó", departamento: "Antioquia" },
  { value: "LA_CEJA", label: "La Ceja", departamento: "Antioquia" },
  { value: "LA_ESTRELLA", label: "La Estrella", departamento: "Antioquia" },
  { value: "LA_PINTADA", label: "La Pintada", departamento: "Antioquia" },
  { value: "LA_UNION", label: "La Unión", departamento: "Antioquia" },
  { value: "LIBORINA", label: "Liborina", departamento: "Antioquia" },
  { value: "MACEO", label: "Maceo", departamento: "Antioquia" },
  { value: "MARINILLA", label: "Marinilla", departamento: "Antioquia" },
  { value: "MONTEBELLO", label: "Montebello", departamento: "Antioquia" },
  { value: "MURINDO", label: "Murindó", departamento: "Antioquia" },
  { value: "MUTATA", label: "Mutatá", departamento: "Antioquia" },
  { value: "NARINO", label: "Nariño", departamento: "Antioquia" },
  { value: "NECHI", label: "Nechí", departamento: "Antioquia" },
  { value: "NECOCLI", label: "Necoclí", departamento: "Antioquia" },
  { value: "OLAYA", label: "Olaya", departamento: "Antioquia" },
  { value: "PENOL", label: "Peñol", departamento: "Antioquia" },
  { value: "PEQUE", label: "Peque", departamento: "Antioquia" },
  { value: "PUEBLORRICO", label: "Pueblorrico", departamento: "Antioquia" },
  { value: "PUERTO_BERRIO", label: "Puerto Berrío", departamento: "Antioquia" },
  { value: "PUERTO_NARE", label: "Puerto Nare", departamento: "Antioquia" },
  { value: "PUERTO_TRIUNFO", label: "Puerto Triunfo", departamento: "Antioquia" },
  { value: "REMEDIOS", label: "Remedios", departamento: "Antioquia" },
  { value: "RETIRO", label: "Retiro", departamento: "Antioquia" },
  { value: "RIONEGRO", label: "Rionegro", departamento: "Antioquia" },
  { value: "SABANALARGA", label: "Sabanalarga", departamento: "Antioquia" },
  { value: "SABANETA", label: "Sabaneta", departamento: "Antioquia" },
  { value: "SALGAR", label: "Salgar", departamento: "Antioquia" },
  { value: "SAN_CARLOS", label: "San Carlos", departamento: "Antioquia" },
  { value: "SAN_FRANCISCO", label: "San Francisco", departamento: "Antioquia" },
  { value: "SAN_JERONIMO", label: "San Jerónimo", departamento: "Antioquia" },
  { value: "SAN_JOSE_DE_LA_MONTANA", label: "San José de la Montaña", departamento: "Antioquia" },
  { value: "SAN_JUAN_DE_URABA", label: "San Juan de Urabá", departamento: "Antioquia" },
  { value: "SAN_LUIS", label: "San Luis", departamento: "Antioquia" },
  { value: "SAN_PEDRO", label: "San Pedro de los Milagros", departamento: "Antioquia" },
  { value: "SAN_PEDRO_DE_URABA", label: "San Pedro de Urabá", departamento: "Antioquia" },
  { value: "SAN_RAFAEL", label: "San Rafael", departamento: "Antioquia" },
  { value: "SAN_ROQUE", label: "San Roque", departamento: "Antioquia" },
  { value: "SAN_VICENTE", label: "San Vicente Ferrer", departamento: "Antioquia" },
  { value: "SANTA_BARBARA", label: "Santa Bárbara", departamento: "Antioquia" },
  { value: "SANTA_FE_DE_ANTIOQUIA", label: "Santa Fe de Antioquia", departamento: "Antioquia" },
  { value: "SANTA_ROSA_DE_OSOS", label: "Santa Rosa de Osos", departamento: "Antioquia" },
  { value: "SANTO_DOMINGO", label: "Santo Domingo", departamento: "Antioquia" },
  { value: "SEGOVIA", label: "Segovia", departamento: "Antioquia" },
  { value: "SONSON", label: "Sonsón", departamento: "Antioquia" },
  { value: "SOPETRAN", label: "Sopetrán", departamento: "Antioquia" },
  { value: "TAMESIS", label: "Támesis", departamento: "Antioquia" },
  { value: "TARAZA", label: "Tarazá", departamento: "Antioquia" },
  { value: "TARSO", label: "Tarso", departamento: "Antioquia" },
  { value: "TITIRIBI", label: "Titiribí", departamento: "Antioquia" },
  { value: "TOLEDO", label: "Toledo", departamento: "Antioquia" },
  { value: "TURBO", label: "Turbo", departamento: "Antioquia" },
  { value: "URAMITA", label: "Uramita", departamento: "Antioquia" },
  { value: "URRAO", label: "Urrao", departamento: "Antioquia" },
  { value: "VALDIVIA", label: "Valdivia", departamento: "Antioquia" },
  { value: "VALPARAISO", label: "Valparaíso", departamento: "Antioquia" },
  { value: "VEGACHI", label: "Vegachí", departamento: "Antioquia" },
  { value: "VENECIA", label: "Venecia", departamento: "Antioquia" },
  { value: "VIGIA_DEL_FUERTE", label: "Vigía del Fuerte", departamento: "Antioquia" },
  { value: "YALI", label: "Yalí", departamento: "Antioquia" },
  { value: "YARUMAL", label: "Yarumal", departamento: "Antioquia" },
  { value: "YOLOMBO", label: "Yolombó", departamento: "Antioquia" },
  { value: "YONDO", label: "Yondó", departamento: "Antioquia" },
  { value: "ZARAGOZA", label: "Zaragoza", departamento: "Antioquia" },

  // Arauca
  { value: "ARAUCA", label: "Arauca", departamento: "Arauca" },
  { value: "ARAUQUITA", label: "Arauquita", departamento: "Arauca" },
  { value: "CRAVO_NORTE", label: "Cravo Norte", departamento: "Arauca" },
  { value: "FORTUL", label: "Fortul", departamento: "Arauca" },
  { value: "PUERTO_RONDON", label: "Puerto Rondón", departamento: "Arauca" },
  { value: "SARAVENA", label: "Saravena", departamento: "Arauca" },
  { value: "TAME", label: "Tame", departamento: "Arauca" },

  // Atlántico
  { value: "BARRANQUILLA", label: "Barranquilla", departamento: "Atlántico" },
  { value: "BARANOA", label: "Baranoa", departamento: "Atlántico" },
  { value: "CAMPO_DE_LA_CRUZ", label: "Campo de la Cruz", departamento: "Atlántico" },
  { value: "CANDELARIA", label: "Candelaria", departamento: "Atlántico" },
  { value: "GALAPA", label: "Galapa", departamento: "Atlántico" },
  { value: "JUAN_DE_ACOSTA", label: "Juan de Acosta", departamento: "Atlántico" },
  { value: "LURUACO", label: "Luruaco", departamento: "Atlántico" },
  { value: "MALAMBO", label: "Malambo", departamento: "Atlántico" },
  { value: "MANATI", label: "Manatí", departamento: "Atlántico" },
  { value: "PALMAR_DE_VARELA", label: "Palmar de Varela", departamento: "Atlántico" },
  { value: "PIOJO", label: "Piojó", departamento: "Atlántico" },
  { value: "POLONUEVO", label: "Polonuevo", departamento: "Atlántico" },
  { value: "PONEDERA", label: "Ponedera", departamento: "Atlántico" },
  { value: "PUERTO_COLOMBIA", label: "Puerto Colombia", departamento: "Atlántico" },
  { value: "REPELON", label: "Repelón", departamento: "Atlántico" },
  { value: "SABANAGRANDE", label: "Sabanagrande", departamento: "Atlántico" },
  { value: "SABANALARGA_ATL", label: "Sabanalarga", departamento: "Atlántico" },
  { value: "SANTA_LUCIA", label: "Santa Lucía", departamento: "Atlántico" },
  { value: "SANTO_TOMAS", label: "Santo Tomás", departamento: "Atlántico" },
  { value: "SOLEDAD", label: "Soledad", departamento: "Atlántico" },
  { value: "SUAN", label: "Suan", departamento: "Atlántico" },
  { value: "TUBARA", label: "Tubará", departamento: "Atlántico" },
  { value: "USIACURI", label: "Usiacurí", departamento: "Atlántico" },

  // Bogotá D.C.
  { value: "BOGOTA", label: "Bogotá D.C.", departamento: "Bogotá D.C." },

  // Bolívar
  { value: "CARTAGENA", label: "Cartagena de Indias", departamento: "Bolívar" },
  { value: "ACHI", label: "Achí", departamento: "Bolívar" },
  { value: "ALTOS_DEL_ROSARIO", label: "Altos del Rosario", departamento: "Bolívar" },
  { value: "ARENAL", label: "Arenal", departamento: "Bolívar" },
  { value: "ARJONA", label: "Arjona", departamento: "Bolívar" },
  { value: "ARROYOHONDO", label: "Arroyohondo", departamento: "Bolívar" },
  { value: "BARRANCO_DE_LOBA", label: "Barranco de Loba", departamento: "Bolívar" },
  { value: "CALAMAR", label: "Calamar", departamento: "Bolívar" },
  { value: "CANTAGALLO", label: "Cantagallo", departamento: "Bolívar" },
  { value: "CICUCO", label: "Cicuco", departamento: "Bolívar" },
  { value: "CORDOBA", label: "Córdoba", departamento: "Bolívar" },
  { value: "CLEMENCIA", label: "Clemencia", departamento: "Bolívar" },
  { value: "EL_CARMEN_DE_BOLIVAR", label: "El Carmen de Bolívar", departamento: "Bolívar" },
  { value: "EL_GUAMO", label: "El Guamo", departamento: "Bolívar" },
  { value: "EL_PENON", label: "El Peñón", departamento: "Bolívar" },
  { value: "HATILLO_DE_LOBA", label: "Hatillo de Loba", departamento: "Bolívar" },
  { value: "MAGANGUE", label: "Magangué", departamento: "Bolívar" },
  { value: "MAHATES", label: "Mahates", departamento: "Bolívar" },
  { value: "MARGARITA", label: "Margarita", departamento: "Bolívar" },
  { value: "MARIA_LA_BAJA", label: "María la Baja", departamento: "Bolívar" },
  { value: "MOMPOS", label: "Mompós", departamento: "Bolívar" },
  { value: "MORALES", label: "Morales", departamento: "Bolívar" },
  { value: "NOROSI", label: "Norosí", departamento: "Bolívar" },
  { value: "PINILLOS", label: "Pinillos", departamento: "Bolívar" },
  { value: "REGIDOR", label: "Regidor", departamento: "Bolívar" },
  { value: "RIO_VIEJO", label: "Río Viejo", departamento: "Bolívar" },
  { value: "SAN_CRISTOBAL", label: "San Cristóbal", departamento: "Bolívar" },
  { value: "SAN_ESTANISLAO", label: "San Estanislao", departamento: "Bolívar" },
  { value: "SAN_FERNANDO", label: "San Fernando", departamento: "Bolívar" },
  { value: "SAN_JACINTO", label: "San Jacinto", departamento: "Bolívar" },
  { value: "SAN_JUAN_NEPOMUCENO", label: "San Juan Nepomuceno", departamento: "Bolívar" },
  { value: "SAN_MARTIN_DE_LOBA", label: "San Martín de Loba", departamento: "Bolívar" },
  { value: "SAN_PABLO", label: "San Pablo", departamento: "Bolívar" },
  { value: "SANTA_CATALINA", label: "Santa Catalina", departamento: "Bolívar" },
  { value: "SANTA_ROSA", label: "Santa Rosa", departamento: "Bolívar" },
  { value: "SANTA_ROSA_DEL_SUR", label: "Santa Rosa del Sur", departamento: "Bolívar" },
  { value: "SIMITI", label: "Simití", departamento: "Bolívar" },
  { value: "SOPLAVIENTO", label: "Soplaviento", departamento: "Bolívar" },
  { value: "TALAIGUA_NUEVO", label: "Talaigua Nuevo", departamento: "Bolívar" },
  { value: "TIQUISIO", label: "Tiquisio", departamento: "Bolívar" },
  { value: "TURBACO", label: "Turbaco", departamento: "Bolívar" },
  { value: "TURBANA", label: "Turbaná", departamento: "Bolívar" },
  { value: "VILLANUEVA", label: "Villanueva", departamento: "Bolívar" },
  { value: "ZAMBRANO", label: "Zambrano", departamento: "Bolívar" },

  // Boyacá
  { value: "TUNJA", label: "Tunja", departamento: "Boyacá" },
  { value: "CHIQUINQUIRA", label: "Chiquinquirá", departamento: "Boyacá" },
  { value: "DUITAMA", label: "Duitama", departamento: "Boyacá" },
  { value: "PAIPA", label: "Paipa", departamento: "Boyacá" },
  { value: "PUERTO_BOYACA", label: "Puerto Boyacá", departamento: "Boyacá" },
  { value: "SOGAMOSO", label: "Sogamoso", departamento: "Boyacá" },
  { value: "VILLA_DE_LEYVA", label: "Villa de Leyva", departamento: "Boyacá" },
  { value: "AQUITANIA", label: "Aquitania", departamento: "Boyacá" },
  { value: "ARCABUCO", label: "Arcabuco", departamento: "Boyacá" },
  { value: "BELEN", label: "Belén", departamento: "Boyacá" },
  { value: "BOAVITA", label: "Boavita", departamento: "Boyacá" },
  { value: "COMBITA", label: "Cómbita", departamento: "Boyacá" },
  { value: "CUCaita", label: "Cucaita", departamento: "Boyacá" },
  { value: "GARAGOA", label: "Garagoa", departamento: "Boyacá" },
  { value: "GUATEQUE", label: "Guateque", departamento: "Boyacá" },
  { value: "JENESANO", label: "Jenesano", departamento: "Boyacá" },
  { value: "MONIQUIRA", label: "Moniquirá", departamento: "Boyacá" },
  { value: "MOTAVITA", label: "Motavita", departamento: "Boyacá" },
  { value: "NOBSA", label: "Nobsa", departamento: "Boyacá" },
  { value: "RAMIRIQUI", label: "Ramiriquí", departamento: "Boyacá" },
  { value: "SAMACA", label: "Samacá", departamento: "Boyacá" },
  { value: "SANTA_ROSA_DE_VITERBO", label: "Santa Rosa de Viterbo", departamento: "Boyacá" },
  { value: "SOATA", label: "Soatá", departamento: "Boyacá" },
  { value: "SOTAQUIRA", label: "Sotaquirá", departamento: "Boyacá" },
  { value: "TIBASOSA", label: "Tibasosa", departamento: "Boyacá" },
  { value: "TOCA", label: "Toca", departamento: "Boyacá" },

  // Caldas
  { value: "MANIZALES", label: "Manizales", departamento: "Caldas" },
  { value: "AGUADAS", label: "Aguadas", departamento: "Caldas" },
  { value: "ANSERMA", label: "Anserma", departamento: "Caldas" },
  { value: "ARANZAZU", label: "Aranzazu", departamento: "Caldas" },
  { value: "BELALCAZAR", label: "Belalcázar", departamento: "Caldas" },
  { value: "CHINCHINA", label: "Chinchiná", departamento: "Caldas" },
  { value: "FILADELFIA", label: "Filadelfia", departamento: "Caldas" },
  { value: "LA_DORADA", label: "La Dorada", departamento: "Caldas" },
  { value: "LA_MERCED", label: "La Merced", departamento: "Caldas" },
  { value: "MANZANARES", label: "Manzanares", departamento: "Caldas" },
  { value: "MARMATO", label: "Marmato", departamento: "Caldas" },
  { value: "MARQUETALIA", label: "Marquetalia", departamento: "Caldas" },
  { value: "MARULANDA", label: "Marulanda", departamento: "Caldas" },
  { value: "NEIRA", label: "Neira", departamento: "Caldas" },
  { value: "NORCASIA", label: "Norcasia", departamento: "Caldas" },
  { value: "PACORA", label: "Pácora", departamento: "Caldas" },
  { value: "PALESTINA", label: "Palestina", departamento: "Caldas" },
  { value: "PENSILVANIA", label: "Pensilvania", departamento: "Caldas" },
  { value: "RIOSUCIO", label: "Riosucio", departamento: "Caldas" },
  { value: "RISARALDA", label: "Risaralda", departamento: "Caldas" },
  { value: "SALAMINA", label: "Salamina", departamento: "Caldas" },
  { value: "SAMANA", label: "Samaná", departamento: "Caldas" },
  { value: "SAN_JOSE", label: "San José", departamento: "Caldas" },
  { value: "SUPIA", label: "Supía", departamento: "Caldas" },
  { value: "VICTORIA", label: "Victoria", departamento: "Caldas" },
  { value: "VILLAMARIA", label: "Villamaría", departamento: "Caldas" },
  { value: "VITERBO", label: "Viterbo", departamento: "Caldas" },

  // Caquetá
  { value: "FLORENCIA", label: "Florencia", departamento: "Caquetá" },
  { value: "ALBANIA", label: "Albania", departamento: "Caquetá" },
  { value: "BELEN_DE_LOS_ANDAQUIES", label: "Belén de los Andaquíes", departamento: "Caquetá" },
  { value: "CARTAGENA_DEL_CHAIRA", label: "Cartagena del Chairá", departamento: "Caquetá" },
  { value: "CURILLO", label: "Curillo", departamento: "Caquetá" },
  { value: "EL_DONCELLO", label: "El Doncello", departamento: "Caquetá" },
  { value: "EL_PAUJIL", label: "El Paujil", departamento: "Caquetá" },
  { value: "LA_MONTANITA", label: "La Montañita", departamento: "Caquetá" },
  { value: "MILAN", label: "Milán", departamento: "Caquetá" },
  { value: "MORELIA", label: "Morelia", departamento: "Caquetá" },
  { value: "PUERTO_RICO", label: "Puerto Rico", departamento: "Caquetá" },
  { value: "SAN_JOSE_DEL_FRAGUA", label: "San José del Fragua", departamento: "Caquetá" },
  { value: "SAN_VICENTE_DEL_CAGUAN", label: "San Vicente del Caguán", departamento: "Caquetá" },
  { value: "SOLANO", label: "Solano", departamento: "Caquetá" },
  { value: "SOLITA", label: "Solita", departamento: "Caquetá" },
  { value: "VALPARAISO_CAQ", label: "Valparaíso", departamento: "Caquetá" },

  // Casanare
  { value: "YOPAL", label: "Yopal", departamento: "Casanare" },
  { value: "AGUAZUL", label: "Aguazul", departamento: "Casanare" },
  { value: "CHAMEZA", label: "Chámeza", departamento: "Casanare" },
  { value: "HATO_COROZAL", label: "Hato Corozal", departamento: "Casanare" },
  { value: "LA_SALINA", label: "La Salina", departamento: "Casanare" },
  { value: "MANI", label: "Maní", departamento: "Casanare" },
  { value: "MONTERREY", label: "Monterrey", departamento: "Casanare" },
  { value: "NUNCHIA", label: "Nunchía", departamento: "Casanare" },
  { value: "OROCUE", label: "Orocué", departamento: "Casanare" },
  { value: "PAZ_DE_ARIPORO", label: "Paz de Ariporo", departamento: "Casanare" },
  { value: "PORE", label: "Pore", departamento: "Casanare" },
  { value: "RECETOR", label: "Recetor", departamento: "Casanare" },
  { value: "SABANALARGA_CAS", label: "Sabanalarga", departamento: "Casanare" },
  { value: "SACAMA", label: "Sácama", departamento: "Casanare" },
  { value: "SAN_LUIS_DE_PALENQUE", label: "San Luis de Palenque", departamento: "Casanare" },
  { value: "TAMARA", label: "Támara", departamento: "Casanare" },
  { value: "TAURAMENA", label: "Tauramena", departamento: "Casanare" },
  { value: "TRINIDAD", label: "Trinidad", departamento: "Casanare" },
  { value: "VILLANUEVA_CAS", label: "Villanueva", departamento: "Casanare" },

  // Cauca
  { value: "POPAYAN", label: "Popayán", departamento: "Cauca" },
  { value: "CALDONO", label: "Caldono", departamento: "Cauca" },
  { value: "CALOTO", label: "Caloto", departamento: "Cauca" },
  { value: "EL_TAMBO", label: "El Tambo", departamento: "Cauca" },
  { value: "GUAPI", label: "Guapí", departamento: "Cauca" },
  { value: "INZA", label: "Inzá", departamento: "Cauca" },
  { value: "MIRANDA", label: "Miranda", departamento: "Cauca" },
  { value: "PATIA", label: "Patía", departamento: "Cauca" },
  { value: "PIENDAMO", label: "Piendamó", departamento: "Cauca" },
  { value: "PUERTO_TEJADA", label: "Puerto Tejada", departamento: "Cauca" },
  { value: "SANTANDER_DE_QUILICHAO", label: "Santander de Quilichao", departamento: "Cauca" },
  { value: "SILVIA", label: "Silvia", departamento: "Cauca" },

  // Cesar
  { value: "VALLEDUPAR", label: "Valledupar", departamento: "Cesar" },
  { value: "AGUACHICA", label: "Aguachica", departamento: "Cesar" },
  { value: "AGUSTIN_CODAZZI", label: "Agustín Codazzi", departamento: "Cesar" },
  { value: "BECERRIL", label: "Becerril", departamento: "Cesar" },
  { value: "BOSCONIA", label: "Bosconia", departamento: "Cesar" },
  { value: "CHIMICHAGUA", label: "Chimichagua", departamento: "Cesar" },
  { value: "CHIRIGUANA", label: "Chiriguaná", departamento: "Cesar" },
  { value: "CURUMANI", label: "Curumaní", departamento: "Cesar" },
  { value: "EL_COPEY", label: "El Copey", departamento: "Cesar" },
  { value: "EL_PASO", label: "El Paso", departamento: "Cesar" },
  { value: "GAMARRA", label: "Gamarra", departamento: "Cesar" },
  { value: "GONZALEZ", label: "González", departamento: "Cesar" },
  { value: "LA_GLORIA", label: "La Gloria", departamento: "Cesar" },
  { value: "LA_JAGUA_DE_IBIRICO", label: "La Jagua de Ibirico", departamento: "Cesar" },
  { value: "MANAURE", label: "Manaure", departamento: "Cesar" },
  { value: "PAILITAS", label: "Pailitas", departamento: "Cesar" },
  { value: "PELAYA", label: "Pelaya", departamento: "Cesar" },
  { value: "PUEBLO_BELLO", label: "Pueblo Bello", departamento: "Cesar" },
  { value: "RIO_DE_ORO", label: "Río de Oro", departamento: "Cesar" },
  { value: "SAN_ALBERTO", label: "San Alberto", departamento: "Cesar" },
  { value: "SAN_DIEGO", label: "San Diego", departamento: "Cesar" },
  { value: "SAN_MARTIN", label: "San Martín", departamento: "Cesar" },
  { value: "TAMALAMEQUE", label: "Tamalameque", departamento: "Cesar" },

  // Chocó
  { value: "QUIBDO", label: "Quibdó", departamento: "Chocó" },
  { value: "ACANDI", label: "Acandí", departamento: "Chocó" },
  { value: "ALTO_BAUDO", label: "Alto Baudó", departamento: "Chocó" },
  { value: "ATRATO", label: "Atrato", departamento: "Chocó" },
  { value: "BAGADO", label: "Bagadó", departamento: "Chocó" },
  { value: "BAHIA_SOLANO", label: "Bahía Solano", departamento: "Chocó" },
  { value: "BAJO_BAUDO", label: "Bajo Baudó", departamento: "Chocó" },
  { value: "BOJAYA", label: "Bojayá", departamento: "Chocó" },
  { value: "CANTON_DE_SAN_PABLO", label: "Cantón de San Pablo", departamento: "Chocó" },
  { value: "CONDOTO", label: "Condoto", departamento: "Chocó" },
  { value: "ISTMINA", label: "Istmina", departamento: "Chocó" },
  { value: "JURADO", label: "Juradó", departamento: "Chocó" },
  { value: "LITORAL_DEL_SAN_JUAN", label: "Litoral del San Juan", departamento: "Chocó" },
  { value: "LLORO", label: "Lloró", departamento: "Chocó" },
  { value: "NOVITA", label: "Nóvita", departamento: "Chocó" },
  { value: "NUQUI", label: "Nuquí", departamento: "Chocó" },
  { value: "RIO_QUITO", label: "Río Quito", departamento: "Chocó" },
  { value: "RIOSUCIO_CHO", label: "Riosucio", departamento: "Chocó" },
  { value: "SAN_JOSE_DEL_PALMAR", label: "San José del Palmar", departamento: "Chocó" },
  { value: "SIPI", label: "Sipí", departamento: "Chocó" },
  { value: "TADO", label: "Tadó", departamento: "Chocó" },
  { value: "UNGUIA", label: "Unguía", departamento: "Chocó" },

  // Córdoba
  { value: "MONTERIA", label: "Montería", departamento: "Córdoba" },
  { value: "CERETE", label: "Cereté", departamento: "Córdoba" },
  { value: "CHIMA", label: "Chimá", departamento: "Córdoba" },
  { value: "CHINU", label: "Chinú", departamento: "Córdoba" },
  { value: "CIENAGA_DE_ORO", label: "Ciénaga de Oro", departamento: "Córdoba" },
  { value: "LORICA", label: "Lorica", departamento: "Córdoba" },
  { value: "LOS_CORDOBAS", label: "Los Córdobas", departamento: "Córdoba" },
  { value: "MOMIL", label: "Momil", departamento: "Córdoba" },
  { value: "MONTELIBANO", label: "Montelíbano", departamento: "Córdoba" },
  { value: "PLANETA_RICA", label: "Planeta Rica", departamento: "Córdoba" },
  { value: "PUEBLO_NUEVO", label: "Pueblo Nuevo", departamento: "Córdoba" },
  { value: "PUERTO_ESCONDIDO", label: "Puerto Escondido", departamento: "Córdoba" },
  { value: "PUERTO_LIBERTADOR", label: "Puerto Libertador", departamento: "Córdoba" },
  { value: "SAHAGUN", label: "Sahagún", departamento: "Córdoba" },
  { value: "SAN_ANTERO", label: "San Antero", departamento: "Córdoba" },
  { value: "SAN_BERNARDO_DEL_VIENTO", label: "San Bernardo del Viento", departamento: "Córdoba" },
  { value: "SAN_PELAYO", label: "San Pelayo", departamento: "Córdoba" },
  { value: "TIERRALTA", label: "Tierralta", departamento: "Córdoba" },
  { value: "TUCHIN", label: "Tuchín", departamento: "Córdoba" },
  { value: "VALENCIA", label: "Valencia", departamento: "Córdoba" },

  // Cundinamarca
  { value: "AGUA_DE_DIOS", label: "Agua de Dios", departamento: "Cundinamarca" },
  { value: "ALBAN", label: "Albán", departamento: "Cundinamarca" },
  { value: "ANAPOIMA", label: "Anapoima", departamento: "Cundinamarca" },
  { value: "ANOLAIMA", label: "Anolaima", departamento: "Cundinamarca" },
  { value: "APULO", label: "Apulo", departamento: "Cundinamarca" },
  { value: "ARBELAEZ", label: "Arbeláez", departamento: "Cundinamarca" },
  { value: "BELTRAN", label: "Beltrán", departamento: "Cundinamarca" },
  { value: "BITUIMA", label: "Bituima", departamento: "Cundinamarca" },
  { value: "BOJACA", label: "Bojacá", departamento: "Cundinamarca" },
  { value: "CABRERA", label: "Cabrera", departamento: "Cundinamarca" },
  { value: "CACHIPAY", label: "Cachipay", departamento: "Cundinamarca" },
  { value: "CAJICA", label: "Cajicá", departamento: "Cundinamarca" },
  { value: "CAPARRAPI", label: "Caparrapí", departamento: "Cundinamarca" },
  { value: "CAQUEZA", label: "Cáqueza", departamento: "Cundinamarca" },
  { value: "CARMEN_DE_CARUPA", label: "Carmen de Carupa", departamento: "Cundinamarca" },
  { value: "CHAGUANI", label: "Chaguaní", departamento: "Cundinamarca" },
  { value: "CHIA", label: "Chía", departamento: "Cundinamarca" },
  { value: "CHIPAQUE", label: "Chipaque", departamento: "Cundinamarca" },
  { value: "CHOACHI", label: "Choachí", departamento: "Cundinamarca" },
  { value: "CHOCONTA", label: "Chocontá", departamento: "Cundinamarca" },
  { value: "COGUA", label: "Cogua", departamento: "Cundinamarca" },
  { value: "COTA", label: "Cota", departamento: "Cundinamarca" },
  { value: "CUCUNUBA", label: "Cucunubá", departamento: "Cundinamarca" },
  { value: "EL_COLEGIO", label: "El Colegio", departamento: "Cundinamarca" },
  { value: "EL_PENON_CUN", label: "El Peñón", departamento: "Cundinamarca" },
  { value: "EL_ROSAL", label: "El Rosal", departamento: "Cundinamarca" },
  { value: "FACATATIVA", label: "Facatativá", departamento: "Cundinamarca" },
  { value: "FOMEQUE", label: "Fómeque", departamento: "Cundinamarca" },
  { value: "FOSCA", label: "Fosca", departamento: "Cundinamarca" },
  { value: "FUNZA", label: "Funza", departamento: "Cundinamarca" },
  { value: "FUQUENE", label: "Fúquene", departamento: "Cundinamarca" },
  { value: "FUSAGASUGA", label: "Fusagasugá", departamento: "Cundinamarca" },
  { value: "GACHALA", label: "Gachalá", departamento: "Cundinamarca" },
  { value: "GACHANCIPA", label: "Gachancipá", departamento: "Cundinamarca" },
  { value: "GACHETA", label: "Gachetá", departamento: "Cundinamarca" },
  { value: "GAMA", label: "Gama", departamento: "Cundinamarca" },
  { value: "GIRARDOT", label: "Girardot", departamento: "Cundinamarca" },
  { value: "GRANADA_CUN", label: "Granada", departamento: "Cundinamarca" },
  { value: "GUACHETA", label: "Guachetá", departamento: "Cundinamarca" },
  { value: "GUADUAS", label: "Guaduas", departamento: "Cundinamarca" },
  { value: "GUASCA", label: "Guasca", departamento: "Cundinamarca" },
  { value: "GUATAQUI", label: "Guataquí", departamento: "Cundinamarca" },
  { value: "GUATAVITA", label: "Guatavita", departamento: "Cundinamarca" },
  { value: "GUAYABAL_DE_SIQUIMA", label: "Guayabal de Síquima", departamento: "Cundinamarca" },
  { value: "GUAYABETAL", label: "Guayabetal", departamento: "Cundinamarca" },
  { value: "GUTIERREZ", label: "Gutiérrez", departamento: "Cundinamarca" },
  { value: "JERUSALEN", label: "Jerusalén", departamento: "Cundinamarca" },
  { value: "JUNIN", label: "Junín", departamento: "Cundinamarca" },
  { value: "LA_CALERA", label: "La Calera", departamento: "Cundinamarca" },
  { value: "LA_MESA", label: "La Mesa", departamento: "Cundinamarca" },
  { value: "LA_PALMA", label: "La Palma", departamento: "Cundinamarca" },
  { value: "LA_PENA", label: "La Peña", departamento: "Cundinamarca" },
  { value: "LA_VEGA", label: "La Vega", departamento: "Cundinamarca" },
  { value: "LENGUAZAQUE", label: "Lenguazaque", departamento: "Cundinamarca" },
  { value: "MACHETA", label: "Machetá", departamento: "Cundinamarca" },
  { value: "MADRID", label: "Madrid", departamento: "Cundinamarca" },
  { value: "MANTA", label: "Manta", departamento: "Cundinamarca" },
  { value: "MEDINA", label: "Medina", departamento: "Cundinamarca" },
  { value: "MOSQUERA", label: "Mosquera", departamento: "Cundinamarca" },
  { value: "NEMOCON", label: "Nemocón", departamento: "Cundinamarca" },
  { value: "NILO", label: "Nilo", departamento: "Cundinamarca" },
  { value: "NIMAIMA", label: "Nimaima", departamento: "Cundinamarca" },
  { value: "NOCAIMA", label: "Nocaima", departamento: "Cundinamarca" },
  { value: "PACHO", label: "Pacho", departamento: "Cundinamarca" },
  { value: "PAIME", label: "Paime", departamento: "Cundinamarca" },
  { value: "PANDI", label: "Pandi", departamento: "Cundinamarca" },
  { value: "PARATEBUENO", label: "Paratebueno", departamento: "Cundinamarca" },
  { value: "PASCA", label: "Pasca", departamento: "Cundinamarca" },
  { value: "PUERTO_SALGAR", label: "Puerto Salgar", departamento: "Cundinamarca" },
  { value: "PULI", label: "Pulí", departamento: "Cundinamarca" },
  { value: "QUEBRADANEGRA", label: "Quebradanegra", departamento: "Cundinamarca" },
  { value: "QUETAME", label: "Quetame", departamento: "Cundinamarca" },
  { value: "QUIPILE", label: "Quipile", departamento: "Cundinamarca" },
  { value: "RICAURTE", label: "Ricaurte", departamento: "Cundinamarca" },
  { value: "SAN_ANTONIO_DEL_TEQUENDAMA", label: "San Antonio del Tequendama", departamento: "Cundinamarca" },
  { value: "SAN_BERNARDO", label: "San Bernardo", departamento: "Cundinamarca" },
  { value: "SAN_CAYETANO", label: "San Cayetano", departamento: "Cundinamarca" },
  { value: "SAN_FRANCISCO_CUN", label: "San Francisco", departamento: "Cundinamarca" },
  { value: "SAN_JUAN_DE_RIOSECO", label: "San Juan de Rioseco", departamento: "Cundinamarca" },
  { value: "SASAIMA", label: "Sasaima", departamento: "Cundinamarca" },
  { value: "SESQUILE", label: "Sesquilé", departamento: "Cundinamarca" },
  { value: "SIBATE", label: "Sibaté", departamento: "Cundinamarca" },
  { value: "SILVANIA", label: "Silvania", departamento: "Cundinamarca" },
  { value: "SIMIJACA", label: "Simijaca", departamento: "Cundinamarca" },
  { value: "SOACHA", label: "Soacha", departamento: "Cundinamarca" },
  { value: "SOPO", label: "Sopó", departamento: "Cundinamarca" },
  { value: "SUBACHOQUE", label: "Subachoque", departamento: "Cundinamarca" },
  { value: "SUESCA", label: "Suesca", departamento: "Cundinamarca" },
  { value: "SUPATA", label: "Supatá", departamento: "Cundinamarca" },
  { value: "SUSA", label: "Susa", departamento: "Cundinamarca" },
  { value: "SUTATAUSA", label: "Sutatausa", departamento: "Cundinamarca" },
  { value: "TABIO", label: "Tabio", departamento: "Cundinamarca" },
  { value: "TAUSA", label: "Tausa", departamento: "Cundinamarca" },
  { value: "TENA", label: "Tena", departamento: "Cundinamarca" },
  { value: "TENJO", label: "Tenjo", departamento: "Cundinamarca" },
  { value: "TIBACUY", label: "Tibacuy", departamento: "Cundinamarca" },
  { value: "TIBIRITA", label: "Tibirita", departamento: "Cundinamarca" },
  { value: "TOCAIMA", label: "Tocaima", departamento: "Cundinamarca" },
  { value: "TOCANCIPA", label: "Tocancipá", departamento: "Cundinamarca" },
  { value: "TOPAIPI", label: "Topaipí", departamento: "Cundinamarca" },
  { value: "UBALA", label: "Ubalá", departamento: "Cundinamarca" },
  { value: "UBAQUE", label: "Ubaque", departamento: "Cundinamarca" },
  { value: "UNE", label: "Une", departamento: "Cundinamarca" },
  { value: "UTICA", label: "Útica", departamento: "Cundinamarca" },
  { value: "VENECIA_CUN", label: "Venecia", departamento: "Cundinamarca" },
  { value: "VERGARA", label: "Vergara", departamento: "Cundinamarca" },
  { value: "VIANI", label: "Vianí", departamento: "Cundinamarca" },
  { value: "VILLA_GOMEZ", label: "Villa Gómez", departamento: "Cundinamarca" },
  { value: "VILLAPINZON", label: "Villapinzón", departamento: "Cundinamarca" },
  { value: "VILLETA", label: "Villeta", departamento: "Cundinamarca" },
  { value: "VIOTA", label: "Viotá", departamento: "Cundinamarca" },
  { value: "YACOPI", label: "Yacopí", departamento: "Cundinamarca" },
  { value: "ZIPACON", label: "Zipacón", departamento: "Cundinamarca" },
  { value: "ZIPAQUIRA", label: "Zipaquirá", departamento: "Cundinamarca" },

  // La Guajira
  { value: "RIOHACHA", label: "Riohacha", departamento: "La Guajira" },
  { value: "ALBANIA_GUA", label: "Albania", departamento: "La Guajira" },
  { value: "BARRANCAS", label: "Barrancas", departamento: "La Guajira" },
  { value: "DIBULLA", label: "Dibulla", departamento: "La Guajira" },
  { value: "DISTRACCION", label: "Distracción", departamento: "La Guajira" },
  { value: "EL_MOLINO", label: "El Molino", departamento: "La Guajira" },
  { value: "FONSECA", label: "Fonseca", departamento: "La Guajira" },
  { value: "HATONUEVO", label: "Hatonuevo", departamento: "La Guajira" },
  { value: "LA_JAGUA_DEL_PILAR", label: "La Jagua del Pilar", departamento: "La Guajira" },
  { value: "MAICAO", label: "Maicao", departamento: "La Guajira" },
  { value: "MANAURE_GUA", label: "Manaure", departamento: "La Guajira" },
  { value: "SAN_JUAN_DEL_CESAR", label: "San Juan del Cesar", departamento: "La Guajira" },
  { value: "URIBIA", label: "Uribia", departamento: "La Guajira" },
  { value: "URUMITA", label: "Urumita", departamento: "La Guajira" },
  { value: "VILLANUEVA_GUA", label: "Villanueva", departamento: "La Guajira" },

  // Huila
  { value: "NEIVA", label: "Neiva", departamento: "Huila" },
  { value: "GARZON", label: "Garzón", departamento: "Huila" },
  { value: "GIGANTE", label: "Gigante", departamento: "Huila" },
  { value: "LA_PLATA", label: "La Plata", departamento: "Huila" },
  { value: "PALERMO", label: "Palermo", departamento: "Huila" },
  { value: "PITALITO", label: "Pitalito", departamento: "Huila" },
  { value: "RIVERA", label: "Rivera", departamento: "Huila" },
  { value: "SAN_AGUSTIN", label: "San Agustín", departamento: "Huila" },
  { value: "TIMANA", label: "Timaná", departamento: "Huila" },
  { value: "VILLAVIEJA", label: "Villavieja", departamento: "Huila" },

  // Magdalena
  { value: "SANTA_MARTA", label: "Santa Marta", departamento: "Magdalena" },
  { value: "ARACATACA", label: "Aracataca", departamento: "Magdalena" },
  { value: "ARIGUANI", label: "Ariguaní", departamento: "Magdalena" },
  { value: "CERRO_DE_SAN_ANTONIO", label: "Cerro de San Antonio", departamento: "Magdalena" },
  { value: "CHIVOLO", label: "Chivoló", departamento: "Magdalena" },
  { value: "CIENAGA", label: "Ciénaga", departamento: "Magdalena" },
  { value: "CONCORDIA_MAG", label: "Concordia", departamento: "Magdalena" },
  { value: "EL_BANCO", label: "El Banco", departamento: "Magdalena" },
  { value: "EL_PINON", label: "El Piñón", departamento: "Magdalena" },
  { value: "EL_RETEN", label: "El Retén", departamento: "Magdalena" },
  { value: "FUNDACION", label: "Fundación", departamento: "Magdalena" },
  { value: "GUAMAL", label: "Guamal", departamento: "Magdalena" },
  { value: "PEDRAZA", label: "Pedraza", departamento: "Magdalena" },
  { value: "PIJINO_DEL_CARMEN", label: "Pijiño del Carmen", departamento: "Magdalena" },
  { value: "PIVIJAY", label: "Pivijay", departamento: "Magdalena" },
  { value: "PLATO", label: "Plato", departamento: "Magdalena" },
  { value: "PUEBLOVIEJO", label: "Puebloviejo", departamento: "Magdalena" },
  { value: "REMOLINO", label: "Remolino", departamento: "Magdalena" },
  { value: "SABANAS_DE_SAN_ANGEL", label: "Sabanas de San Ángel", departamento: "Magdalena" },
  { value: "SALAMINA_MAG", label: "Salamina", departamento: "Magdalena" },
  { value: "SAN_SEBASTIAN_DE_BUENAVISTA", label: "San Sebastián de Buenavista", departamento: "Magdalena" },
  { value: "SAN_ZENON", label: "San Zenón", departamento: "Magdalena" },
  { value: "SANTA_ANA", label: "Santa Ana", departamento: "Magdalena" },
  { value: "SANTA_BARBARA_DE_PINTO", label: "Santa Bárbara de Pinto", departamento: "Magdalena" },
  { value: "SITIONUEVO", label: "Sitionuevo", departamento: "Magdalena" },
  { value: "TENERIFE", label: "Tenerife", departamento: "Magdalena" },
  { value: "ZAPAYAN", label: "Zapayán", departamento: "Magdalena" },
  { value: "ZONA_BANANERA", label: "Zona Bananera", departamento: "Magdalena" },

  // Meta
  { value: "VILLAVICENCIO", label: "Villavicencio", departamento: "Meta" },
  { value: "ACACIAS", label: "Acacías", departamento: "Meta" },
  { value: "BARRANCA_DE_UPIA", label: "Barranca de Upía", departamento: "Meta" },
  { value: "CABUYARO", label: "Cabuyaro", departamento: "Meta" },
  { value: "CASTILLA_LA_NUEVA", label: "Castilla la Nueva", departamento: "Meta" },
  { value: "CUMARAL", label: "Cumaral", departamento: "Meta" },
  { value: "EL_CALVARIO", label: "El Calvario", departamento: "Meta" },
  { value: "EL_CASTILLO", label: "El Castillo", departamento: "Meta" },
  { value: "EL_DORADO", label: "El Dorado", departamento: "Meta" },
  { value: "FUENTE_DE_ORO", label: "Fuente de Oro", departamento: "Meta" },
  { value: "GRANADA_MET", label: "Granada", departamento: "Meta" },
  { value: "GUAMAL_MET", label: "Guamal", departamento: "Meta" },
  { value: "LA_MACARENA", label: "La Macarena", departamento: "Meta" },
  { value: "LEJANIAS", label: "Lejanías", departamento: "Meta" },
  { value: "MAPIRIPAN", label: "Mapiripán", departamento: "Meta" },
  { value: "MESETAS", label: "Mesetas", departamento: "Meta" },
  { value: "PUERTO_GAITAN", label: "Puerto Gaitán", departamento: "Meta" },
  { value: "PUERTO_LLERAS", label: "Puerto Lleras", departamento: "Meta" },
  { value: "PUERTO_LOPEZ", label: "Puerto López", departamento: "Meta" },
  { value: "PUERTO_RICO_MET", label: "Puerto Rico", departamento: "Meta" },
  { value: "RESTREPO", label: "Restrepo", departamento: "Meta" },
  { value: "SAN_CARLOS_DE_GUAROA", label: "San Carlos de Guaroa", departamento: "Meta" },
  { value: "SAN_JUAN_DE_ARAMA", label: "San Juan de Arama", departamento: "Meta" },
  { value: "SAN_JUANITO", label: "San Juanito", departamento: "Meta" },
  { value: "SAN_MARTIN_MET", label: "San Martín", departamento: "Meta" },
  { value: "URIBE", label: "Uribe", departamento: "Meta" },
  { value: "VILLAHERMOSA", label: "Villahermosa", departamento: "Meta" },
  { value: "VISTAHERMOSA", label: "Vistahermosa", departamento: "Meta" },

  // Nariño
  { value: "PASTO", label: "Pasto", departamento: "Nariño" },
  { value: "IPIALES", label: "Ipiales", departamento: "Nariño" },
  { value: "LA_UNION_NAR", label: "La Unión", departamento: "Nariño" },
  { value: "SANDONA", label: "Sandona", departamento: "Nariño" },
  { value: "TUMACO", label: "Tumaco", departamento: "Nariño" },
  { value: "TUQUERRES", label: "Túquerres", departamento: "Nariño" },

  // Norte de Santander
  { value: "CUCUTA", label: "Cúcuta", departamento: "Norte de Santander" },
  { value: "ABREGO", label: "Ábrego", departamento: "Norte de Santander" },
  { value: "CACHIRA", label: "Cáchira", departamento: "Norte de Santander" },
  { value: "CHINACOTA", label: "Chinácota", departamento: "Norte de Santander" },
  { value: "CHITAGA", label: "Chitagá", departamento: "Norte de Santander" },
  { value: "CONVENCION", label: "Convención", departamento: "Norte de Santander" },
  { value: "EL_CARMEN", label: "El Carmen", departamento: "Norte de Santander" },
  { value: "EL_TARRA", label: "El Tarra", departamento: "Norte de Santander" },
  { value: "GRAMALOTE", label: "Gramalote", departamento: "Norte de Santander" },
  { value: "LOS_PATIOS", label: "Los Patios", departamento: "Norte de Santander" },
  { value: "OCANA", label: "Ocaña", departamento: "Norte de Santander" },
  { value: "PAMPLONA", label: "Pamplona", departamento: "Norte de Santander" },
  { value: "PAMPLONITA", label: "Pamplonita", departamento: "Norte de Santander" },
  { value: "SALAZAR", label: "Salazar de las Palmas", departamento: "Norte de Santander" },
  { value: "SAN_CAYETANO_NS", label: "San Cayetano", departamento: "Norte de Santander" },
  { value: "SANTIAGO", label: "Santiago", departamento: "Norte de Santander" },
  { value: "TIBU", label: "Tibú", departamento: "Norte de Santander" },
  { value: "TOLEDO_NS", label: "Toledo", departamento: "Norte de Santander" },
  { value: "VILLA_DEL_ROSARIO", label: "Villa del Rosario", departamento: "Norte de Santander" },

  // Putumayo
  { value: "MOCOA", label: "Mocoa", departamento: "Putumayo" },
  { value: "ORITO", label: "Orito", departamento: "Putumayo" },
  { value: "PUERTO_ASIS", label: "Puerto Asís", departamento: "Putumayo" },
  { value: "PUERTO_GUZMAN", label: "Puerto Guzmán", departamento: "Putumayo" },
  { value: "SAN_MIGUEL", label: "San Miguel", departamento: "Putumayo" },
  { value: "SIBUNDOY", label: "Sibundoy", departamento: "Putumayo" },
  { value: "VALLE_DEL_GUAMUEZ", label: "Valle del Guamuez", departamento: "Putumayo" },
  { value: "VILLAGARZON", label: "Villagarzón", departamento: "Putumayo" },

  // Quindío
  { value: "ARMENIA_QUI", label: "Armenia", departamento: "Quindío" },
  { value: "BUENAVISTA", label: "Buenavista", departamento: "Quindío" },
  { value: "CALARCA", label: "Calarcá", departamento: "Quindío" },
  { value: "CIRCASIA", label: "Circasia", departamento: "Quindío" },
  { value: "CORDOBA_QUI", label: "Córdoba", departamento: "Quindío" },
  { value: "FILANDIA", label: "Filandia", departamento: "Quindío" },
  { value: "GENOVA", label: "Génova", departamento: "Quindío" },
  { value: "LA_TEBAIDA", label: "La Tebaida", departamento: "Quindío" },
  { value: "MONTENEGRO", label: "Montenegro", departamento: "Quindío" },
  { value: "PIJAO", label: "Pijao", departamento: "Quindío" },
  { value: "QUIMBAYA", label: "Quimbaya", departamento: "Quindío" },
  { value: "SALENTO", label: "Salento", departamento: "Quindío" },

  // Risaralda
  { value: "PEREIRA", label: "Pereira", departamento: "Risaralda" },
  { value: "APIA", label: "Apía", departamento: "Risaralda" },
  { value: "BALBOA", label: "Balboa", departamento: "Risaralda" },
  { value: "BELEN_DE_UMBRIA", label: "Belén de Umbría", departamento: "Risaralda" },
  { value: "DOSQUEBRADAS", label: "Dosquebradas", departamento: "Risaralda" },
  { value: "GUATICA", label: "Guática", departamento: "Risaralda" },
  { value: "LA_CELIA", label: "La Celia", departamento: "Risaralda" },
  { value: "LA_VIRGINIA", label: "La Virginia", departamento: "Risaralda" },
  { value: "MARSELLA", label: "Marsella", departamento: "Risaralda" },
  { value: "MISTRATO", label: "Mistrató", departamento: "Risaralda" },
  { value: "PUEBLO_RICO", label: "Pueblo Rico", departamento: "Risaralda" },
  { value: "QUINCHIA", label: "Quinchía", departamento: "Risaralda" },
  { value: "SANTA_ROSA_DE_CABAL", label: "Santa Rosa de Cabal", departamento: "Risaralda" },
  { value: "SANTUARIO", label: "Santuario", departamento: "Risaralda" },

  // Santander
  { value: "BUCARAMANGA", label: "Bucaramanga", departamento: "Santander" },
  { value: "BARBOSA_SAN", label: "Barbosa", departamento: "Santander" },
  { value: "BARRANCABERMEJA", label: "Barrancabermeja", departamento: "Santander" },
  { value: "FLORIDABLANCA", label: "Floridablanca", departamento: "Santander" },
  { value: "GIRON", label: "Girón", departamento: "Santander" },
  { value: "LEBRIJA", label: "Lebrija", departamento: "Santander" },
  { value: "MALAGA", label: "Málaga", departamento: "Santander" },
  { value: "PIEDECUESTA", label: "Piedecuesta", departamento: "Santander" },
  { value: "SAN_GIL", label: "San Gil", departamento: "Santander" },
  { value: "SOCORRO", label: "Socorro", departamento: "Santander" },
  { value: "VELEZ", label: "Vélez", departamento: "Santander" },

  // Sucre
  { value: "SINCELEJO", label: "Sincelejo", departamento: "Sucre" },
  { value: "COROZAL", label: "Corozal", departamento: "Sucre" },
  { value: "COVENAS", label: "Coveñas", departamento: "Sucre" },
  { value: "SAN_MARCOS", label: "San Marcos", departamento: "Sucre" },
  { value: "SAN_ONOFRE", label: "San Onofre", departamento: "Sucre" },
  { value: "SANTIAGO_DE_TOLU", label: "Santiago de Tolú", departamento: "Sucre" },
  { value: "TOLUVIEJO", label: "Toluviejo", departamento: "Sucre" },

  // Tolima
  { value: "IBAGUE", label: "Ibagué", departamento: "Tolima" },
  { value: "ARMERO_GUAYABAL", label: "Armero Guayabal", departamento: "Tolima" },
  { value: "CAJAMARCA", label: "Cajamarca", departamento: "Tolima" },
  { value: "CARMEN_DE_APICALA", label: "Carmen de Apicalá", departamento: "Tolima" },
  { value: "CHAPARRAL", label: "Chaparral", departamento: "Tolima" },
  { value: "ESPINAL", label: "Espinal", departamento: "Tolima" },
  { value: "FLANDES", label: "Flandes", departamento: "Tolima" },
  { value: "FRESNO", label: "Fresno", departamento: "Tolima" },
  { value: "GUAMO", label: "Guamo", departamento: "Tolima" },
  { value: "HERVEO", label: "Herveo", departamento: "Tolima" },
  { value: "HONDA", label: "Honda", departamento: "Tolima" },
  { value: "LERIDA", label: "Lérida", departamento: "Tolima" },
  { value: "LIBANO", label: "Líbano", departamento: "Tolima" },
  { value: "MARIQUITA", label: "Mariquita", departamento: "Tolima" },
  { value: "MELGAR", label: "Melgar", departamento: "Tolima" },
  { value: "ORTEGA", label: "Ortega", departamento: "Tolima" },
  { value: "PRADO", label: "Prado", departamento: "Tolima" },
  { value: "PURIFICACION", label: "Purificación", departamento: "Tolima" },
  { value: "RIOBLANCO", label: "Rioblanco", departamento: "Tolima" },
  { value: "ROVIRA", label: "Rovira", departamento: "Tolima" },
  { value: "SALDANA", label: "Saldaña", departamento: "Tolima" },
  { value: "SAN_ANTONIO", label: "San Antonio", departamento: "Tolima" },
  { value: "SAN_LUIS_TOL", label: "San Luis", departamento: "Tolima" },
  { value: "VENADILLO", label: "Venadillo", departamento: "Tolima" },

  // Valle del Cauca
  { value: "CALI", label: "Cali", departamento: "Valle del Cauca" },
  { value: "ANDALUCIA", label: "Andalucía", departamento: "Valle del Cauca" },
  { value: "BUENAVENTURA", label: "Buenaventura", departamento: "Valle del Cauca" },
  { value: "BUGA", label: "Buga", departamento: "Valle del Cauca" },
  { value: "BUGALAGRANDE", label: "Bugalagrande", departamento: "Valle del Cauca" },
  { value: "CAICEDONIA", label: "Caicedonia", departamento: "Valle del Cauca" },
  { value: "CALIMA", label: "Calima", departamento: "Valle del Cauca" },
  { value: "CANDELARIA_VAL", label: "Candelaria", departamento: "Valle del Cauca" },
  { value: "CARTAGO", label: "Cartago", departamento: "Valle del Cauca" },
  { value: "DAGUA", label: "Dagua", departamento: "Valle del Cauca" },
  { value: "EL_CERRITO", label: "El Cerrito", departamento: "Valle del Cauca" },
  { value: "FLORIDA", label: "Florida", departamento: "Valle del Cauca" },
  { value: "GINEBRA", label: "Ginebra", departamento: "Valle del Cauca" },
  { value: "GUACARI", label: "Guacarí", departamento: "Valle del Cauca" },
  { value: "JAMUNDI", label: "Jamundí", departamento: "Valle del Cauca" },
  { value: "LA_CUMBRE", label: "La Cumbre", departamento: "Valle del Cauca" },
  { value: "LA_UNION_VAL", label: "La Unión", departamento: "Valle del Cauca" },
  { value: "LA_VICTORIA", label: "La Victoria", departamento: "Valle del Cauca" },
  { value: "OBANDO", label: "Obando", departamento: "Valle del Cauca" },
  { value: "PALMIRA", label: "Palmira", departamento: "Valle del Cauca" },
  { value: "PRADERA", label: "Pradera", departamento: "Valle del Cauca" },
  { value: "ROLDANILLO", label: "Roldanillo", departamento: "Valle del Cauca" },
  { value: "SAN_PEDRO_VAL", label: "San Pedro", departamento: "Valle del Cauca" },
  { value: "SEVILLA", label: "Sevilla", departamento: "Valle del Cauca" },
  { value: "TORO", label: "Toro", departamento: "Valle del Cauca" },
  { value: "TRUJILLO", label: "Trujillo", departamento: "Valle del Cauca" },
  { value: "TULUA", label: "Tuluá", departamento: "Valle del Cauca" },
  { value: "YUMBO", label: "Yumbo", departamento: "Valle del Cauca" },
  { value: "ZARZAL", label: "Zarzal", departamento: "Valle del Cauca" },
]
